spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: r1
              uri: lb://CLIENT-SERVICE
              predicates:
                - Path= /api/clients/**
            - id: r2
              uri: lb://PRODUIT-SERVICE
              predicates:
                - Path= /api/produits/**
            - id: r3
              uri: lb://FACTURATION-SERVICE
              predicates:
                  - Path= /api/factures/**