spring.application.name=gateway-service
server.port=8080
spring.cloud.discovery.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# Resilience4j Rate Limiter Configuration
resilience4j.ratelimiter.instances.default.limit-for-period=10
resilience4j.ratelimiter.instances.default.limit-refresh-period=1s
resilience4j.ratelimiter.instances.default.timeout-duration=0s

resilience4j.ratelimiter.instances.clients.limit-for-period=10
resilience4j.ratelimiter.instances.clients.limit-refresh-period=1s
resilience4j.ratelimiter.instances.clients.timeout-duration=0s

resilience4j.ratelimiter.instances.produits.limit-for-period=10
resilience4j.ratelimiter.instances.produits.limit-refresh-period=1s
resilience4j.ratelimiter.instances.produits.timeout-duration=0s

resilience4j.ratelimiter.instances.factures.limit-for-period=10
resilience4j.ratelimiter.instances.factures.limit-refresh-period=100s
resilience4j.ratelimiter.instances.factures.timeout-duration=0s

