spring.application.name=test-service
server.port=8085

feign.circuitbreaker.enabled=false

resilience4j.retry.instances.produit-service.max-attempts=3
resilience4j.retry.instances.produit-service.wait-duration=500ms
resilience4j.retry.instances.produit-service.enable-exponential-backoff=false

resilience4j.circuitbreaker.instances.produit-service.sliding-window-size=5
resilience4j.circuitbreaker.instances.produit-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.produit-service.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.produit-service.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.produit-service.automatic-transition-from-open-to-half-open-enabled=true

management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents,retries,retryevents
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true
